/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Entidades.Main;
import Persistencia.ConexionBD;
import Persistencia.IConexionBD;
import Persistencia.IPersonaDAO;
import Persistencia.PersonaDAO;


public class Inicial extends javax.swing.JFrame {

    /**
     * Creates new form Inicial
     */
    public Inicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnRegistrarVariasPersonas = new javax.swing.JButton();
        btnOpciones = new javax.swing.JButton();
        btnRegistrarPersona = new javax.swing.JButton();
        btnAceptarPersona = new javax.swing.JButton();
        btnAceptar5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Menu inicial");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 190, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 70));

        btnRegistrarVariasPersonas.setBackground(new java.awt.Color(0, 102, 204));
        btnRegistrarVariasPersonas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRegistrarVariasPersonas.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarVariasPersonas.setText("Registrar Varias Personas");
        btnRegistrarVariasPersonas.setBorder(null);
        btnRegistrarVariasPersonas.setContentAreaFilled(false);
        btnRegistrarVariasPersonas.setOpaque(true);
        btnRegistrarVariasPersonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarVariasPersonasActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrarVariasPersonas, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 230, 37));

        btnOpciones.setBackground(new java.awt.Color(0, 102, 204));
        btnOpciones.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnOpciones.setForeground(new java.awt.Color(255, 255, 255));
        btnOpciones.setText("Menu opciones");
        btnOpciones.setBorder(null);
        btnOpciones.setContentAreaFilled(false);
        btnOpciones.setOpaque(true);
        btnOpciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpcionesActionPerformed(evt);
            }
        });
        jPanel1.add(btnOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 210, 37));

        btnRegistrarPersona.setBackground(new java.awt.Color(0, 102, 204));
        btnRegistrarPersona.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRegistrarPersona.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarPersona.setText("Registrar Persona Nueva");
        btnRegistrarPersona.setBorder(null);
        btnRegistrarPersona.setContentAreaFilled(false);
        btnRegistrarPersona.setOpaque(true);
        btnRegistrarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarPersonaActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrarPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 230, 37));

        btnAceptarPersona.setBackground(new java.awt.Color(0, 102, 204));
        btnAceptarPersona.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAceptarPersona.setForeground(new java.awt.Color(255, 255, 255));
        btnAceptarPersona.setText("Atender Persona Existente");
        btnAceptarPersona.setBorder(null);
        btnAceptarPersona.setContentAreaFilled(false);
        btnAceptarPersona.setOpaque(true);
        btnAceptarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarPersonaActionPerformed(evt);
            }
        });
        jPanel1.add(btnAceptarPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 210, 37));

        btnAceptar5.setBackground(new java.awt.Color(0, 102, 204));
        btnAceptar5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAceptar5.setForeground(new java.awt.Color(255, 255, 255));
        btnAceptar5.setText("Mostrar Lista de Personas");
        btnAceptar5.setBorder(null);
        btnAceptar5.setContentAreaFilled(false);
        btnAceptar5.setOpaque(true);
        btnAceptar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptar5ActionPerformed(evt);
            }
        });
        jPanel1.add(btnAceptar5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 210, 37));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarVariasPersonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarVariasPersonasActionPerformed
  RegistrarVariosUsuarios ase= new RegistrarVariosUsuarios();
  ase.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnRegistrarVariasPersonasActionPerformed

    private void btnOpcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpcionesActionPerformed
    
        /*Menu a= new  Menu();
    a.setVisible(true);
    this.dispose();
    */
      
      
    }//GEN-LAST:event_btnOpcionesActionPerformed

    private void btnRegistrarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarPersonaActionPerformed
   IConexionBD conexionbd= new ConexionBD();
   IPersonaDAO personaDAO= new PersonaDAO(conexionbd);
        Registrar_Persona rp= new  Registrar_Persona(personaDAO);
   rp.setVisible(true);
     this.dispose();
    }//GEN-LAST:event_btnRegistrarPersonaActionPerformed

    private void btnAceptarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarPersonaActionPerformed
      APersonaExistente as= new  APersonaExistente();
      as.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAceptarPersonaActionPerformed

    private void btnAceptar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptar5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAceptar5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              //  new Inicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar5;
    private javax.swing.JButton btnAceptarPersona;
    private javax.swing.JButton btnOpciones;
    private javax.swing.JButton btnRegistrarPersona;
    private javax.swing.JButton btnRegistrarVariasPersonas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
