/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Entidades.Main;
import Entidades.Tramite;
import Persistencia.ConexionBD;
import Persistencia.IConexionBD;
import Persistencia.IPersonaDAO;
import Persistencia.ITramiteDAO;
import Persistencia.PersonaDAO;
import Persistencia.TramiteDAO;

public class Inicial extends javax.swing.JFrame {

    /**
     * Creates new form Inicial
     */
    public Inicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnRegistrarVariasPersonas = new javax.swing.JButton();
        btnRegistrarPersona = new javax.swing.JButton();
        btnAceptarPersona = new javax.swing.JButton();
        btnHistoGeneral = new javax.swing.JButton();
        btnAceptar6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Menu inicial");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 190, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 70));

        btnRegistrarVariasPersonas.setBackground(new java.awt.Color(0, 102, 204));
        btnRegistrarVariasPersonas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRegistrarVariasPersonas.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarVariasPersonas.setText("Registrar Varias Personas");
        btnRegistrarVariasPersonas.setBorder(null);
        btnRegistrarVariasPersonas.setContentAreaFilled(false);
        btnRegistrarVariasPersonas.setOpaque(true);
        btnRegistrarVariasPersonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarVariasPersonasActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrarVariasPersonas, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 230, 37));

        btnRegistrarPersona.setBackground(new java.awt.Color(0, 102, 204));
        btnRegistrarPersona.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRegistrarPersona.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarPersona.setText("Registrar Persona Nueva");
        btnRegistrarPersona.setBorder(null);
        btnRegistrarPersona.setContentAreaFilled(false);
        btnRegistrarPersona.setOpaque(true);
        btnRegistrarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarPersonaActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrarPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 230, 37));

        btnAceptarPersona.setBackground(new java.awt.Color(0, 102, 204));
        btnAceptarPersona.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAceptarPersona.setForeground(new java.awt.Color(255, 255, 255));
        btnAceptarPersona.setText("Atender Persona Existente");
        btnAceptarPersona.setBorder(null);
        btnAceptarPersona.setContentAreaFilled(false);
        btnAceptarPersona.setOpaque(true);
        btnAceptarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarPersonaActionPerformed(evt);
            }
        });
        jPanel1.add(btnAceptarPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 210, 37));

        btnHistoGeneral.setBackground(new java.awt.Color(0, 102, 204));
        btnHistoGeneral.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnHistoGeneral.setForeground(new java.awt.Color(255, 255, 255));
        btnHistoGeneral.setText("Historial general");
        btnHistoGeneral.setBorder(null);
        btnHistoGeneral.setContentAreaFilled(false);
        btnHistoGeneral.setOpaque(true);
        btnHistoGeneral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoGeneralActionPerformed(evt);
            }
        });
        jPanel1.add(btnHistoGeneral, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 210, 37));

        btnAceptar6.setBackground(new java.awt.Color(0, 102, 204));
        btnAceptar6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAceptar6.setForeground(new java.awt.Color(255, 255, 255));
        btnAceptar6.setText("Mostrar Lista de Personas");
        btnAceptar6.setBorder(null);
        btnAceptar6.setContentAreaFilled(false);
        btnAceptar6.setOpaque(true);
        btnAceptar6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptar6ActionPerformed(evt);
            }
        });
        jPanel1.add(btnAceptar6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 210, 37));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarVariasPersonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarVariasPersonasActionPerformed
        IConexionBD conexionbd = new ConexionBD();
        IPersonaDAO personaDAO = new PersonaDAO(conexionbd);
        RegistrarVariosUsuarios ase = new RegistrarVariosUsuarios(personaDAO);
        ase.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegistrarVariasPersonasActionPerformed

    private void btnRegistrarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarPersonaActionPerformed
        IConexionBD conexionbd = new ConexionBD();
        IPersonaDAO personaDAO = new PersonaDAO(conexionbd);
        Registrar_Persona rp = new Registrar_Persona(personaDAO);
        rp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegistrarPersonaActionPerformed

    private void btnAceptarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarPersonaActionPerformed
        APersonaExistente as = new APersonaExistente();
        as.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAceptarPersonaActionPerformed

    private void btnHistoGeneralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoGeneralActionPerformed
        IConexionBD conexionbd = new ConexionBD();
        IPersonaDAO personaDAO = new PersonaDAO(conexionbd);
        ITramiteDAO tramiteDAO = new TramiteDAO(conexionbd);

        HistorialGeneral co = new HistorialGeneral(personaDAO, tramiteDAO);
        co.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnHistoGeneralActionPerformed

    private void btnAceptar6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptar6ActionPerformed
        IConexionBD conexionbd = new ConexionBD();
        IPersonaDAO personaDAO = new PersonaDAO(conexionbd);
        Consultas con = new Consultas(personaDAO);
        con.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAceptar6ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar6;
    private javax.swing.JButton btnAceptarPersona;
    private javax.swing.JButton btnHistoGeneral;
    private javax.swing.JButton btnRegistrarPersona;
    private javax.swing.JButton btnRegistrarVariasPersonas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
