package GUI;

import Entidades.Persona;
import Persistencia.ConexionBD;
import Persistencia.IConexionBD;
import Persistencia.ILicenciaDAO;
import Persistencia.IPlacaDAO;
import Persistencia.ITramiteDAO;
import Persistencia.IVehiculoDAO;
import Persistencia.LicenciaDAO;
import Persistencia.PlacaDAO;
import Persistencia.TramiteDAO;
import Persistencia.VehiculoDAO;
import Utilidades.EncriptacionUtils;
import javax.swing.JOptionPane;

/**
 *
 * @author IVAN
 */
public class Menu extends javax.swing.JFrame {

    //prueba
    private Persona persona;

    public Menu(Persona persona) {
        this.persona = persona;
        initComponents();

        lblperso.setText(persona.getNombre() + " " + persona.getApellidoPaterno() + " " + persona.getApellidoMaterno());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVolver = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnSolicitarLicencia = new javax.swing.JButton();
        btnHistorial = new javax.swing.JButton();
        btnSolicitarPlacas = new javax.swing.JButton();
        btnAceptar6 = new javax.swing.JButton();
        lblperso = new javax.swing.JLabel();
        btnRenovarLicencia = new javax.swing.JButton();
        btnHistorialPlacas = new javax.swing.JButton();
        btnRenovarPlacas = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnRegistrarV1 = new javax.swing.JButton();

        btnVolver.setBackground(new java.awt.Color(0, 102, 204));
        btnVolver.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("Volver");
        btnVolver.setBorder(null);
        btnVolver.setContentAreaFilled(false);
        btnVolver.setOpaque(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 102, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Menu de opciones");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 260, -1));

        btnSolicitarLicencia.setBackground(new java.awt.Color(0, 102, 204));
        btnSolicitarLicencia.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSolicitarLicencia.setForeground(new java.awt.Color(255, 255, 255));
        btnSolicitarLicencia.setText("Solicitar Licencia");
        btnSolicitarLicencia.setBorder(null);
        btnSolicitarLicencia.setContentAreaFilled(false);
        btnSolicitarLicencia.setOpaque(true);
        btnSolicitarLicencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolicitarLicenciaActionPerformed(evt);
            }
        });

        btnHistorial.setBackground(new java.awt.Color(0, 102, 204));
        btnHistorial.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnHistorial.setForeground(new java.awt.Color(255, 255, 255));
        btnHistorial.setText("Consultar Historial ");
        btnHistorial.setBorder(null);
        btnHistorial.setContentAreaFilled(false);
        btnHistorial.setOpaque(true);
        btnHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistorialActionPerformed(evt);
            }
        });

        btnSolicitarPlacas.setBackground(new java.awt.Color(0, 102, 204));
        btnSolicitarPlacas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSolicitarPlacas.setForeground(new java.awt.Color(255, 255, 255));
        btnSolicitarPlacas.setText("Solicitar Placas");
        btnSolicitarPlacas.setBorder(null);
        btnSolicitarPlacas.setContentAreaFilled(false);
        btnSolicitarPlacas.setOpaque(true);
        btnSolicitarPlacas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolicitarPlacasActionPerformed(evt);
            }
        });

        btnAceptar6.setBackground(new java.awt.Color(51, 102, 255));
        btnAceptar6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAceptar6.setForeground(new java.awt.Color(255, 255, 255));
        btnAceptar6.setText("Volver");
        btnAceptar6.setBorder(null);
        btnAceptar6.setContentAreaFilled(false);
        btnAceptar6.setOpaque(true);
        btnAceptar6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptar6ActionPerformed(evt);
            }
        });

        lblperso.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblperso.setForeground(new java.awt.Color(0, 102, 204));
        lblperso.setText("a");

        btnRenovarLicencia.setBackground(new java.awt.Color(0, 102, 204));
        btnRenovarLicencia.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRenovarLicencia.setForeground(new java.awt.Color(255, 255, 255));
        btnRenovarLicencia.setText("Renovar Licencia");
        btnRenovarLicencia.setBorder(null);
        btnRenovarLicencia.setContentAreaFilled(false);
        btnRenovarLicencia.setOpaque(true);
        btnRenovarLicencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRenovarLicenciaActionPerformed(evt);
            }
        });

        btnHistorialPlacas.setBackground(new java.awt.Color(0, 102, 204));
        btnHistorialPlacas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnHistorialPlacas.setForeground(new java.awt.Color(255, 255, 255));
        btnHistorialPlacas.setText("Registrar Vehiculo");
        btnHistorialPlacas.setBorder(null);
        btnHistorialPlacas.setContentAreaFilled(false);
        btnHistorialPlacas.setOpaque(true);
        btnHistorialPlacas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistorialPlacasActionPerformed(evt);
            }
        });

        btnRenovarPlacas.setBackground(new java.awt.Color(0, 102, 204));
        btnRenovarPlacas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRenovarPlacas.setForeground(new java.awt.Color(255, 255, 255));
        btnRenovarPlacas.setText("Renovar Placas");
        btnRenovarPlacas.setBorder(null);
        btnRenovarPlacas.setContentAreaFilled(false);
        btnRenovarPlacas.setOpaque(true);
        btnRenovarPlacas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRenovarPlacasActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 204));
        jLabel7.setText("Nombre cliente:");

        btnRegistrarV1.setBackground(new java.awt.Color(0, 102, 204));
        btnRegistrarV1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRegistrarV1.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarV1.setText("Historial Placas");
        btnRegistrarV1.setBorder(null);
        btnRegistrarV1.setContentAreaFilled(false);
        btnRegistrarV1.setOpaque(true);
        btnRegistrarV1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarV1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnHistorialPlacas, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrarV1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnSolicitarLicencia, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnRenovarLicencia, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnRenovarPlacas, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(56, 56, 56)
                                .addComponent(btnSolicitarPlacas, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(61, 61, 61)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAceptar6, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(82, 82, 82))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(lblperso, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblperso)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSolicitarPlacas, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRenovarPlacas, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHistorialPlacas, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSolicitarLicencia, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRenovarLicencia, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAceptar6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrarV1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(154, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 394));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptar6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptar6ActionPerformed
        Inicial in = new Inicial();
        in.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAceptar6ActionPerformed

    private void btnRenovarLicenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRenovarLicenciaActionPerformed
        IConexionBD conexionbd = new ConexionBD();
        ILicenciaDAO licenciadao = new LicenciaDAO(conexionbd);
        ITramiteDAO tramitedao = new TramiteDAO(conexionbd);

        if (licenciadao.verificarLicencia(persona.getId_persona())) {

            RenovarLicencia li = new RenovarLicencia(tramitedao, licenciadao, persona);
            li.setVisible(true);

            this.dispose();

        } else {
            JOptionPane.showMessageDialog(this, "Esta persona no tiene una licencia registrada.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }


    }//GEN-LAST:event_btnRenovarLicenciaActionPerformed

    private void btnHistorialPlacasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialPlacasActionPerformed
        IConexionBD conexionbd = new ConexionBD();
        IVehiculoDAO vehiculodao = new VehiculoDAO(conexionbd);
        RegistrarVehiculo ve = new RegistrarVehiculo(vehiculodao, persona);
        ve.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnHistorialPlacasActionPerformed

    private void btnRenovarPlacasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRenovarPlacasActionPerformed
        IConexionBD conexionbd = new ConexionBD();
        IVehiculoDAO vehiculodao = new VehiculoDAO(conexionbd);
        ILicenciaDAO licenciadao = new LicenciaDAO(conexionbd);
        IPlacaDAO placadao=new PlacaDAO(conexionbd);

        if (licenciadao.verificarLicencia(persona.getId_persona())) {

            RenovarPlacas sp = new RenovarPlacas(persona, vehiculodao,placadao);
            sp.setVisible(true);
            this.dispose();

        } else {
            JOptionPane.showMessageDialog(this, "Esta persona no tiene una licencia registrada.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }


    }//GEN-LAST:event_btnRenovarPlacasActionPerformed

    private void btnSolicitarPlacasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolicitarPlacasActionPerformed
        IConexionBD conexionbd = new ConexionBD();
        IVehiculoDAO vehiculodao = new VehiculoDAO(conexionbd);
        IPlacaDAO placadao = new PlacaDAO(conexionbd);
        ILicenciaDAO licenciadao = new LicenciaDAO(conexionbd);

        if (licenciadao.verificarLicencia(persona.getId_persona())) {

            SolicitarPlacas pl = new SolicitarPlacas(persona, vehiculodao, placadao);
            pl.setVisible(true);
            this.dispose();

        } else {
            JOptionPane.showMessageDialog(this, "Esta persona no tiene una licencia registrada.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }


    }//GEN-LAST:event_btnSolicitarPlacasActionPerformed

    private void btnHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialActionPerformed
        IConexionBD conexionbd = new ConexionBD();
        ITramiteDAO tramite = new TramiteDAO(conexionbd);
        Historial hs = new Historial(persona, tramite);
        hs.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnHistorialActionPerformed

    private void btnSolicitarLicenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolicitarLicenciaActionPerformed

        IConexionBD conexionbd = new ConexionBD();
        ILicenciaDAO licenciadao = new LicenciaDAO(conexionbd);
        ITramiteDAO tramitedao = new TramiteDAO(conexionbd);

        // Verificar si la persona ya tiene una licencia
        if (licenciadao.verificarLicencia(persona.getId_persona())) {
            JOptionPane.showMessageDialog(this, "Esta persona ya tiene una licencia registrada.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        // Si no tiene una licencia registrada, continuar con la solicitud de licencia
        Licencias li = new Licencias(tramitedao, licenciadao, persona);
        li.setVisible(true);
        this.dispose();


    }//GEN-LAST:event_btnSolicitarLicenciaActionPerformed

    private void btnRegistrarV1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarV1ActionPerformed
     IConexionBD conexionbd = new ConexionBD();
        IVehiculoDAO vehiculodao = new VehiculoDAO(conexionbd);
        IPlacaDAO placadao = new PlacaDAO(conexionbd);
        
         PlacasVehiculo pl = new PlacasVehiculo(persona, vehiculodao, placadao);
            pl.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_btnRegistrarV1ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar6;
    private javax.swing.JButton btnHistorial;
    private javax.swing.JButton btnHistorialPlacas;
    private javax.swing.JButton btnRegistrarV1;
    private javax.swing.JButton btnRenovarLicencia;
    private javax.swing.JButton btnRenovarPlacas;
    private javax.swing.JButton btnSolicitarLicencia;
    private javax.swing.JButton btnSolicitarPlacas;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblperso;
    // End of variables declaration//GEN-END:variables
}
