package GUI;

import Entidades.Persona;
import Persistencia.IPersonaDAO;
import Persistencia.PersonaDAO;
import Utilidades.EncriptacionUtils;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author IVAN
 */
public class RegistrarVariosUsuarios extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarVariosUsuarios
     */
    IPersonaDAO personaDAO;

    public RegistrarVariosUsuarios(IPersonaDAO personaDAO) {
        initComponents();
        this.personaDAO = personaDAO;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt = new javax.swing.JTable();
        prueba1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registar a varias personas");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 340, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 70));

        btnCancelar.setBackground(new java.awt.Color(204, 0, 0));
        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(null);
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.setOpaque(true);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 550, 88, 37));

        btnAceptar.setBackground(new java.awt.Color(0, 102, 204));
        btnAceptar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAceptar.setForeground(new java.awt.Color(255, 255, 255));
        btnAceptar.setText("Aceptar");
        btnAceptar.setBorder(null);
        btnAceptar.setContentAreaFilled(false);
        btnAceptar.setOpaque(true);
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 550, 88, 37));

        btnVolver.setBackground(new java.awt.Color(0, 102, 204));
        btnVolver.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("Volver");
        btnVolver.setBorder(null);
        btnVolver.setContentAreaFilled(false);
        btnVolver.setOpaque(true);
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 550, 88, 37));

        jt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido Paterno", "Apellido Materno", "RFC", "Teléfono", "¿Es discapacitado?", "Fecha"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jt);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 740, 350));

        prueba1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        prueba1.setForeground(new java.awt.Color(0, 102, 204));
        prueba1.setText("Ingrese los datos de las personas:");
        jPanel1.add(prueba1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 814, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 662, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void agregarVariasPersonas() {
        boolean dis = true;

        for (int i = 0; i < jt.getRowCount(); i++) {
            for (int j = 0; j < jt.getColumnCount(); j++) {
                if (jt.getValueAt(i, j) == null) {
                    JOptionPane.showMessageDialog(null, "Falta una casilla");
                    return;
                }
            }
        }

        int rowCount = jt.getRowCount();
        int colCount = jt.getColumnCount();

        for (int i = 0; i < rowCount; i++) {
            String nombre = (String) jt.getValueAt(i, 0);
            String apellidoPaterno = (String) jt.getValueAt(i, 1);
            String apellidoMaterno = (String) jt.getValueAt(i, 2);
            String rfc = (String) jt.getValueAt(i, 3);
            String telefono = (String) jt.getValueAt(i, 4);
            String fechaNacimiento = (String) jt.getValueAt(i, 6);

            if ("Si".equalsIgnoreCase((String) jt.getValueAt(i, 5))) {
                dis = true;
            } else if (jt.getValueAt(i, 5) == null) {
                dis = false;
            }

            // Expresiones regulares
            String regexRfc = "[a-zA-Z0-9]+";
            String regexTexto = "[a-zA-ZñÑáéíóúÁÉÍÓÚ\\s]+";
            String regexTelefono = "\\d{10}";

            // Validar que no se pueda agregar números y caracteres especiales a apellidoMaterno, apellidoPaterno y Nombre
            if (!apellidoMaterno.matches(regexTexto) || !apellidoPaterno.matches(regexTexto) || !nombre.matches(regexTexto)) {
                JOptionPane.showMessageDialog(null, "Apellido materno, apellido paterno y nombre solo pueden contener letras");
                continue; // Salir de la iteración actual y pasar a la siguiente persona
            }

            // Validar que no se pueda agregar texto y caracteres especiales a Telefono
            if (!telefono.matches(regexTelefono)) {
                JOptionPane.showMessageDialog(null, "Teléfono solo puede contener números de 10 dígitos");
                continue; // Salir de la iteración actual y pasar a la siguiente persona
            }

            // Validar que no se pueda agregar caracteres especiales a RFC
            if (!rfc.matches(regexRfc)) {
                JOptionPane.showMessageDialog(null, "RFC solo puede contener letras y números");
                continue; // Salir de la iteración actual y pasar a la siguiente persona
            }

            String nombreEncriptado = EncriptacionUtils.encriptarNombre(nombre);
            String apaternoEncriptado = EncriptacionUtils.encriptarApellidoPaterno(apellidoPaterno);
            String amaternoEncriptado = EncriptacionUtils.encriptarApellidoMaterno(apellidoMaterno);
            
            Persona nuevaPersona = new Persona();
            nuevaPersona.setRfc(rfc);
            nuevaPersona.setNombre(nombreEncriptado);
            nuevaPersona.setApellidoPaterno(apaternoEncriptado);
            nuevaPersona.setApellidoMaterno(amaternoEncriptado);
            nuevaPersona.setTelefono(telefono);

            SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
            Date fecha = null;
            try {
                fecha = dateFormat.parse(fechaNacimiento);
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(null, "Fecha incorrecta para el usuario: " + nuevaPersona.getNombre());
                return;
            }

            nuevaPersona.setFechaNacimiento(fecha);
            nuevaPersona.setDiscapacitado(dis);

            // Validar que la persona no tenga el mismo rfc
            List<Persona> personasConMismoRfc = personaDAO.buscarVariosRfc(rfc);
            if (!personasConMismoRfc.isEmpty()) {
                JOptionPane.showMessageDialog(null, "La persona con RFC " + rfc + " ya ha sido registrada anteriormente");
                continue; // Salir de la iteración actual y pasar a la siguiente persona
            }
            // Validar que el telefono no este registrado
            List<Persona> personasConMismoTelefono = personaDAO.buscarVariosTelefonos(telefono);
            if (!personasConMismoTelefono.isEmpty()) {
                JOptionPane.showMessageDialog(null, "El número de teléfono " + telefono + " ya está registrado para otra persona");
                continue; // Salir de la iteración actual y pasar a la siguiente persona
            }

            Persona personaGuardada = personaDAO.agregar(nuevaPersona);

            if (personaGuardada == null) {
                JOptionPane.showMessageDialog(null, "Datos vacíos");
            } else {
                JOptionPane.showMessageDialog(null, "Se ha registrado una persona");
            }
        }
    }


    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed

        agregarVariasPersonas();

    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        Inicial a = new Inicial();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarVariosUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarVariosUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarVariosUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarVariosUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                // new RegistrarVariosUsuarios().setVisible(true);
//                new RegistrarVariosUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jt;
    private javax.swing.JLabel prueba1;
    // End of variables declaration//GEN-END:variables
}
