/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Entidades.Licencia;
import Entidades.Persona;
import Persistencia.ConexionBD;
import Persistencia.IConexionBD;
import Persistencia.ILicenciaDAO;
import Persistencia.IPersonaDAO;
import Persistencia.ITramiteDAO;
import Persistencia.PersonaDAO;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 * Clase para renovar una licencia
 *
 * @author IVAN
 */
public class RenovarLicencia extends javax.swing.JFrame {

    /**
     * Objeto de tipo ILicenciaDAO
     */
    private ILicenciaDAO licenciaDAO;
    /**
     * Objeto de ITramiteDAO
     */
    private ITramiteDAO tramiteDAO;
    /**
     * Objeto de tipo Persona
     */
    private Persona persona;

    /**
     * Constructor for the RenovarLicencia class.
     *
     * @param tramiteDAO the data access object for trámites
     * @param licenciaDAO the data access object for licencias
     * @param persona the persona object for which the license is being renewed
     */
    public RenovarLicencia(ITramiteDAO tramiteDAO, ILicenciaDAO licenciaDAO, Persona persona) {
        this.persona = persona;
        initComponents();

        this.tramiteDAO = tramiteDAO;
        this.licenciaDAO = licenciaDAO;

        lblperso.setText(persona.getNombre() + " " + persona.getApellidoPaterno() + " " + persona.getApellidoMaterno());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        lblperso = new javax.swing.JLabel();
        cmbLicencia = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtLicenciaAnt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Renovar Licencia");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 220, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 70));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 204));
        jLabel3.setText("Años de vigencia:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        btnCancelar.setBackground(new java.awt.Color(204, 0, 0));
        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(null);
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.setOpaque(true);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, 88, 37));

        btnAceptar.setBackground(new java.awt.Color(0, 102, 204));
        btnAceptar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAceptar.setForeground(new java.awt.Color(255, 255, 255));
        btnAceptar.setText("Aceptar");
        btnAceptar.setBorder(null);
        btnAceptar.setContentAreaFilled(false);
        btnAceptar.setOpaque(true);
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 88, 37));

        btnVolver.setBackground(new java.awt.Color(0, 102, 204));
        btnVolver.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("Volver");
        btnVolver.setBorder(null);
        btnVolver.setContentAreaFilled(false);
        btnVolver.setOpaque(true);
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 340, 88, 37));

        lblperso.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblperso.setForeground(new java.awt.Color(0, 102, 204));
        lblperso.setText(".................");
        jPanel1.add(lblperso, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 250, -1));

        cmbLicencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        cmbLicencia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 204)));
        jPanel1.add(cmbLicencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 230, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 204));
        jLabel5.setText("Nombre:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 204));
        jLabel6.setText("Número de licencia anterior:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        txtLicenciaAnt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtLicenciaAnt.setForeground(new java.awt.Color(0, 153, 204));
        txtLicenciaAnt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204), 2));
        jPanel1.add(txtLicenciaAnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 240, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Metodo para guardar la nueva licencia
     * @param persona
     */
    public void guardarnuevaLicencia() {
       
        String licenciaAnt = txtLicenciaAnt.getText();

        if (licenciaAnt == null || !licenciaAnt.matches("\\d+")) {
            JOptionPane.showMessageDialog(null, "Ingrese un número de licencia anterior válida (solo números)");
            return;
        }

        Licencia licenciaencon = licenciaDAO.buscarIdyEstado(Integer.parseInt(txtLicenciaAnt.getText()));

        if (licenciaencon == null || !licenciaencon.getPersona().getId_persona().equals(persona.getId_persona())) {
            JOptionPane.showMessageDialog(null, "No se encontró la licencia con esa id, ya se encuentra inactiva, pertenece a otra persona o no se ha seleccionado una persona válida");

        } else {

            licenciaDAO.desactivarLicencia(licenciaencon);

            try {

                Licencia nuevalicencia = new Licencia();

                Calendar cal = Calendar.getInstance();

                Date fechaActual = cal.getTime();

                int precioLicencia = 0;

                String opcion = (String) cmbLicencia.getSelectedItem();
                String estado = "Activa";
                if (opcion.equals("1")) {

                    cal.add(Calendar.YEAR, 1);
                    Date fechaVigencia = cal.getTime();
                    nuevalicencia.setVigencia(fechaVigencia);
                    precioLicencia = precioLicencia + 600;

                } else if (opcion.equals("2")) {

                    cal.add(Calendar.YEAR, 2);
                    Date fechaVigencia = cal.getTime();
                    nuevalicencia.setVigencia(fechaVigencia);

                    precioLicencia = precioLicencia + 900;

                } else if (opcion.equals("3")) {

                    cal.add(Calendar.YEAR, 3);
                    Date fechaVigencia = cal.getTime();
                    nuevalicencia.setVigencia(fechaVigencia);

                    precioLicencia = precioLicencia + 1100;
                }

                if (persona.isDiscapacitado() == true) {

                    String tipo = "Discapacitado";
                    nuevalicencia.setTipo(tipo);
                    precioLicencia = precioLicencia - 400;
                } else {
                    String tipo = "No Discapacitado";
                    nuevalicencia.setTipo(tipo);
                }
                nuevalicencia.setEstado(estado);
                nuevalicencia.setPersona(persona);

                nuevalicencia.setFecha_solicitud(fechaActual);

                nuevalicencia.setPrecio(precioLicencia);

                Licencia licenciaguardar = licenciaDAO.agregar(nuevalicencia);

                if (licenciaguardar == null) {
                    JOptionPane.showMessageDialog(null, "No se ha podido registrar");
                } else {
                    JOptionPane.showMessageDialog(null, "Se ha renovado la licencia");
                    IConexionBD conexionbd = new ConexionBD();
                    IPersonaDAO personaDAO = new PersonaDAO(conexionbd);

                    Reporte r = new Reporte(persona, licenciaguardar);
                    r.setVisible(true);
                    this.dispose();

                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "No se ha podido registrar");
            }

        }

    }

    /**
     * ActionListener for the "Cancelar" button. Clears the text in the
     * "txtLicenciaAnt" field.
     *
     * @param evt the ActionEvent object
     */
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        txtLicenciaAnt.setText("");
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * ActionListener for the "Volver" button. Creates a new Menu object and
     * sets it visible, while disposing the current window.
     *
     * @param evt the ActionEvent object
     */
    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        Menu m = new Menu(persona);
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed
    /**
     * ActionListener for the "Aceptar" button. Calls the
     * "guardarnuevaLicencia()" method to save the new license information.
     *
     * @param evt the ActionEvent object
     */
    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed

        guardarnuevaLicencia();


    }//GEN-LAST:event_btnAceptarActionPerformed

    /**
     * Elementos del frame
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cmbLicencia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblperso;
    private javax.swing.JTextField txtLicenciaAnt;
    // End of variables declaration//GEN-END:variables
}
