/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Entidades.Licencia;
import Entidades.Persona;
import Entidades.Placa;
import Entidades.Tramite;

/**
 *Clase para el reporte
 * @author IVAN
 */
public class Reporte extends javax.swing.JFrame {

    /**
     * Objeto de tipo Persona
     */
    private Persona persona;
    /**
     * Objeto de tipo tramite
     */
    private Tramite tramite;

    /**
     *
     * Constructor de la clase Reporte que crea una instancia de la ventana de
     * reporte de trámite. Inicializa los componentes visuales y establece los
     * valores de los campos de la ventana con los datos proporcionados de la
     * persona y el trámite.
     *
     * @param persona Objeto de la clase Persona que contiene los datos de la
     * persona para el reporte
     * @param tramite Objeto de la clase Tramite (puede ser Placa o Licencia)
     * que contiene los datos del trámite para el reporte
     */
    public Reporte(Persona persona, Tramite tramite) {
        this.persona = persona;
        this.tramite = tramite;
        initComponents();
        lblperso1.setText(persona.getNombre() + " " + persona.getApellidoPaterno() + " " + persona.getApellidoMaterno());
        if (tramite instanceof Placa) {
            lbltipo.setText("Placa");

        }

        if (tramite instanceof Licencia) {
            lbltipo.setText("Licencia");
        }

        lblcosto.setText(String.valueOf(tramite.getPrecio()));
        lblfecha.setText(String.valueOf(tramite.getFecha_solicitud()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblcosto = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblperso1 = new javax.swing.JLabel();
        lbltipo = new javax.swing.JLabel();
        lblfecha = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ticket");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 120, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 70));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 204));
        jLabel3.setText("Costo Tramite:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        btnAceptar.setBackground(new java.awt.Color(0, 102, 204));
        btnAceptar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAceptar.setForeground(new java.awt.Color(255, 255, 255));
        btnAceptar.setText("Aceptar");
        btnAceptar.setBorder(null);
        btnAceptar.setContentAreaFilled(false);
        btnAceptar.setOpaque(true);
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 88, 37));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 204));
        jLabel4.setText("Fecha Tramite:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 204));
        jLabel5.setText("Tipo Tramite:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        lblcosto.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblcosto.setForeground(new java.awt.Color(0, 102, 204));
        lblcosto.setText("---");
        jPanel1.add(lblcosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 220, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 204));
        jLabel7.setText("Nombre Persona:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        lblperso1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblperso1.setForeground(new java.awt.Color(0, 102, 204));
        lblperso1.setText("---");
        jPanel1.add(lblperso1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 220, -1));

        lbltipo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbltipo.setForeground(new java.awt.Color(0, 102, 204));
        lbltipo.setText("---");
        jPanel1.add(lbltipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 220, -1));

        lblfecha.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblfecha.setForeground(new java.awt.Color(0, 102, 204));
        lblfecha.setText("---");
        jPanel1.add(lblfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 270, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
/**
 * Boton para aceptar 
 * @param evt al darle click
 */
    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        Menu m = new Menu(persona);
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAceptarActionPerformed

/**
 * Elementos del frame
 */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblcosto;
    private javax.swing.JLabel lblfecha;
    private javax.swing.JLabel lblperso1;
    private javax.swing.JLabel lbltipo;
    // End of variables declaration//GEN-END:variables
}
