package GUI;

import Entidades.Persona;
import Entidades.Placa;
import Entidades.Vehiculo;
import Persistencia.IPlacaDAO;
import Persistencia.IVehiculoDAO;
import java.util.Calendar;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *Clase para solicitar placas
 * @author IVAN
 */
public class SolicitarPlacas extends javax.swing.JFrame {

    /**
     * Objeto de tipo personas
     */
    private Persona persona;
    /**
     * Objeto de tipo IPLACADAO
     */
    private IPlacaDAO placa;
    /**
     * Objeto de tipo IVehiculaDAO
     */
    private IVehiculoDAO vehiculo;

    /**
     *
     * Constructor de la clase SolicitarPlacas que inicializa los datos de la
     * persona, vehículo y placa.
     *
     * @param persona Objeto Persona que representa la persona que realiza la
     * solicitud de placas
     * @param vehiculo Objeto IVehiculoDAO que representa la interfaz de acceso
     * a datos de vehículos
     * @param placa Objeto IPlacaDAO que representa la interfaz de acceso a
     * datos de placas
     */
    public SolicitarPlacas(Persona persona, IVehiculoDAO vehiculo, IPlacaDAO placa) {
        this.persona = persona;
        this.vehiculo = vehiculo;
        this.placa = placa;
        initComponents();
        lblperso.setText(persona.getNombre() + " " + persona.getApellidoPaterno() + " " + persona.getApellidoMaterno());
        llenarCombo();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        lblperso = new javax.swing.JLabel();
        btnAceptar1 = new javax.swing.JButton();
        cbxVehiculos = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Solicitar Placas");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 220, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 70));

        btnVolver.setBackground(new java.awt.Color(0, 102, 204));
        btnVolver.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("Volver");
        btnVolver.setBorder(null);
        btnVolver.setContentAreaFilled(false);
        btnVolver.setOpaque(true);
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, 88, 37));

        lblperso.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblperso.setForeground(new java.awt.Color(0, 102, 204));
        lblperso.setText("......");
        jPanel1.add(lblperso, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 280, -1));

        btnAceptar1.setBackground(new java.awt.Color(0, 102, 204));
        btnAceptar1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAceptar1.setForeground(new java.awt.Color(255, 255, 255));
        btnAceptar1.setText("Aceptar");
        btnAceptar1.setBorder(null);
        btnAceptar1.setContentAreaFilled(false);
        btnAceptar1.setOpaque(true);
        btnAceptar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptar1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnAceptar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 88, 37));

        jPanel1.add(cbxVehiculos, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 250, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 204));
        jLabel6.setText("Nombre cliente:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Renovar Placas");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 220, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 204));
        jLabel8.setText("Vehiculos:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 204));
        jLabel9.setText("Nombre cliente:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
/**
     *
     * Método privado btnAceptar1ActionPerformed que se ejecuta cuando se
     * presiona el botón "Aceptar1". Invoca al método asere() para procesar la
     * solicitud de placas.
     *
     * @param evt Objeto ActionEvent que representa el evento de acción del
     * botón
     */
    private void btnAceptar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptar1ActionPerformed
        asere();
    }//GEN-LAST:event_btnAceptar1ActionPerformed
    /**
     *
     * Método privado btnVolverActionPerformed que se ejecuta cuando se presiona
     * el botón "Volver". Crea una nueva ventana de Menu con la persona actual y
     * la muestra, y cierra la ventana actual.
     *
     * @param evt Objeto ActionEvent que representa el evento de acción del
     * botón
     */
    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        Menu m = new Menu(persona);
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed
    /**
     *
     * Método público generarPlacaAleatoria que genera una placa aleatoria para
     * un vehículo.
     *
     * La placa consiste en tres letras mayúsculas seguidas de cuatro números.
     *
     * @return String con la placa generada aleatoriamente
     */
    public String generarPlacaAleatoria() {
        String letras = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
        String numeros = "0123456789";
        String placa = "";

        // Agregar tres letras aleatorias
        for (int i = 0; i < 3; i++) {
            int index = (int) (Math.random() * letras.length());
            placa += letras.charAt(index);
        }

        // Agregar cuatro números aleatorios
        for (int i = 0; i < 4; i++) {
            int index = (int) (Math.random() * numeros.length());
            placa += numeros.charAt(index);
          
        }

        return placa;
    }

    /**
     *
     * Método público asere que procesa la solicitud de placas para un vehículo.
     *
     * Verifica si el vehículo ya tiene placas registradas, genera una nueva
     * placa aleatoria,
     *
     * crea una nueva instancia de Placa con los datos de la solicitud, la
     * agrega a través de la interfaz
     *
     * de acceso a datos de placas, y muestra una ventana de reporte con los
     * datos de la persona y la placa.
     */
    public void asere() {
        int precio = 1500;
        Vehiculo vehiculo = (Vehiculo) cbxVehiculos.getSelectedItem();

        Calendar cal = Calendar.getInstance();

        Date fechaActual = cal.getTime();
        if (placa.verificarPlaca(vehiculo.getId_vehiculo())) {
            JOptionPane.showMessageDialog(this, "Este vehiculo ya tiene unas placas registradas.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String numeroPlaca = generarPlacaAleatoria();

        Placa placanueva = new Placa();

        placanueva.setNum_placa(numeroPlaca);
        placanueva.setEstado("Activa");
        placanueva.setVehiculo(vehiculo);
        placanueva.setPersona(persona);
        placanueva.setFecha_solicitud(fechaActual);
        placanueva.setPrecio(precio);
        Placa placaa = placa.agregar(placanueva);
        if (placaa == null) {
            JOptionPane.showMessageDialog(null, "No se pudo comprar la placa");
        } else {
            JOptionPane.showMessageDialog(null, "La placa ha sido comprada con exito ");
            Reporte r = new Reporte(persona, placanueva);
            r.setVisible(true);
            this.dispose();
        }

    }

    /**
     * Metodo para llenar el combobox
     */
    public void llenarCombo() {
        cbxVehiculos.removeAllItems();
        List<Vehiculo> llenaCb = vehiculo.listaAutosCliente(persona.getRfc());
        System.out.println(llenaCb.size());
        if (llenaCb == null) {

        } else {
            Iterator rp = llenaCb.iterator();
            while (rp.hasNext()) {
                Vehiculo vehi = (Vehiculo) rp.next();
                this.cbxVehiculos.addItem(vehi);
            }
        }
    }

    /**
     * Elementos del frame
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar1;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<Vehiculo> cbxVehiculos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblperso;
    // End of variables declaration//GEN-END:variables
}
